-- AlterTable
ALTER TABLE `pool` MODIFY `feePercent` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `last24hRevenueBTC` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `location` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `uptimePercent` DOUBLE NOT NULL DEFAULT 0;
